# Generated by Django 2.2.4 on 2019-11-11 16:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_padre', models.TextField(blank=True)),
                ('nombre_padre', models.TextField(blank=True)),
                ('codigo_hijo', models.TextField(blank=True)),
                ('nombre_hijo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_paciente', models.CharField(max_length=100)),
                ('cedula_paciente', models.CharField(max_length=10)),
                ('diagnostico_paciente', models.CharField(max_length=100)),
                ('cie', models.CharField(max_length=40)),
                ('fecha_atencion', models.DateField(default=datetime.date.today)),
                ('destino_atencion', models.TextField()),
                ('h_salida_base', models.TimeField(default='20:00')),
                ('h_atencion', models.TimeField(default='20:00')),
                ('h_casa_salud', models.TimeField(default='20:00')),
                ('h_llegada_base', models.TimeField(default='20:00')),
                ('kilometraje_base', models.CharField(max_length=100)),
                ('kilometraje_casa_salud', models.CharField(max_length=100)),
                ('kilometraje_retorno_base', models.CharField(max_length=100)),
                ('motivo_traslado', models.TextField()),
                ('observaciones', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('recurso', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
