# Generated by Django 2.2.4 on 2019-08-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
