# Generated by Django 2.2.4 on 2019-08-26 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0002_auto_20190826_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_paciente', models.CharField(max_length=100)),
                ('cedula_paciente', models.CharField(max_length=10)),
                ('diagnostico_paciente', models.CharField(max_length=100)),
                ('cie', models.CharField(max_length=40)),
                ('fecha_atencion', models.DateField(default=datetime.date.today)),
                ('destino_atencion', models.TextField()),
                ('h_salida_base', models.TimeField(default='20:00')),
                ('h_atencion', models.TimeField(default='20:00')),
                ('h_casa_salud', models.TimeField(default='20:00')),
                ('h_llegada_base', models.TimeField(default='20:00')),
                ('kilometraje_base', models.CharField(max_length=100)),
                ('kilometraje_casa_salud', models.CharField(max_length=100)),
                ('kilometraje_retorno_base', models.CharField(max_length=100)),
                ('motivo_traslado', models.TextField()),
                ('observaciones', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
