# Generated by Django 2.2.4 on 2019-08-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0003_hojaruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaruta',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
