# Generated by Django 2.2.4 on 2019-08-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0004_auto_20190826_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaruta',
            name='observaciones',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
