# Generated by Django 2.2.4 on 2019-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0006_auto_20190913_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaruta',
            name='observaciones',
            field=models.TextField(default='Ninguna', max_length=100),
        ),
    ]
