# Generated by Django 2.2.4 on 2019-09-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0007_auto_20190913_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaruta',
            name='observaciones',
            field=models.TextField(),
        ),
    ]
