# Generated by Django 2.2.4 on 2019-09-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0009_ciudad_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='ciudad',
            field=models.CharField(default='Loja', max_length=100),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='recurso',
            field=models.CharField(default='Alfa0', max_length=100),
        ),
    ]
