# Generated by Django 2.2.4 on 2019-09-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0010_auto_20190913_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaruta',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='recurso',
            field=models.CharField(max_length=100),
        ),
    ]
