# Generated by Django 2.2.4 on 2019-09-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaruta', '0011_auto_20190913_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
